export enum ErrorCodes {
  // Authentication Errors
  AUTHENTICATION_ERROR = 'AUTH_001',
  INVALID_TOKEN = 'AUTH_002',
  TOKEN_EXPIRED = 'AUTH_003',
  UNAUTHORIZED = 'AUTH_004',

  // Validation Errors
  VALIDATION_ERROR = 'VAL_001',
  INVALID_INPUT = 'VAL_002',

  // Session Errors
  SESSION_NOT_FOUND = 'SES_001',
  SESSION_ALREADY_COMPLETED = 'SES_002',
  SESSION_ALREADY_EXISTS = 'SES_003',
  SESSION_NOT_ACTIVE = 'SES_004',

  // Group Session Errors
  GROUP_SESSION_FULL = 'GRP_001',
  GROUP_SESSION_NOT_FOUND = 'GRP_002',
  GROUP_SESSION_ALREADY_STARTED = 'GRP_003',
  GROUP_SESSION_NOT_STARTED = 'GRP_004',

  // Resource Errors
  NOT_FOUND = 'RES_001',
  ALREADY_EXISTS = 'RES_002',

  // Concurrency Errors
  CONCURRENCY_ERROR = 'CON_001',
  LOCK_ACQUISITION_FAILED = 'CON_002',

  // External Service Errors
  EXTERNAL_SERVICE_ERROR = 'EXT_001',

  // General Errors
  INTERNAL_ERROR = 'GEN_001',
  OPERATION_FAILED = 'GEN_002'
} 